# Use Ubuntu as the base image
FROM ubuntu:latest

# Set a working directory
WORKDIR /app

# Copy your C source code into the container
COPY multifork.c .

# Install necessary build tools
RUN apt-get update && \
    apt-get install -y gcc

# Compile the C program
RUN gcc -o multifork multifork.c

# Set the entry point for the container
CMD ["./multifork"]
