# Use the official Ubuntu as the base image
FROM ubuntu:latest

# Set the maintainer label (replace with your information)
LABEL maintainer="15-Dollatham"

# Update the package lists and install essential packages including wget
RUN apt update \
    && apt install -y sudo gcc python3 nano vim p7zip-full zip unzip wget \
    && rm -rf /var/lib/apt/lists/*

# Add the current directory (.) to the PATH environment variable
ENV PATH="${PATH}:."

# Set the working directory
WORKDIR /root

# Install Python packages (NumPy and Pandas)
RUN apt update \
    && apt install -y python3-pip \
    && pip3 install numpy pandas

# Copy csine.c and np2pd.py from the current directory to /root in the container
COPY csine.c /root/
COPY np2pd.py /root/

# Download and extract the ml-latest-small.zip file
RUN wget https://files.grouplens.org/datasets/movielens/ml-latest-small.zip && \
    unzip ml-latest-small.zip && \
    rm ml-latest-small.zip

# Start a Bash shell when the container is run
CMD ["/bin/bash"]
