# Use an official Ubuntu as the base image
FROM ubuntu:latest

# Set the maintainer label (replace with your information)
LABEL maintainer="15-Dollatham"

# Install necessary packages (gcc for compiling)
RUN apt update && apt install -y gcc

# Copy the C source code file into the container
COPY afork.c /root/afork.c

# Set the working directory
WORKDIR /root

# Compile the C program
RUN gcc -o afork afork.c

# Start a Bash shell when the container is run
CMD ["/bin/bash"]
